name: itube
description: A YouTube clone-ish
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  bloc: ^9.2.0
  cross_file: ^0.3.5+1
  dartz: ^0.10.1
  desktop_drop: ^0.7.0
  device_preview: ^1.3.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_shaders: ^0.1.3
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^9.0.0
  gap: ^3.0.1
  get_it: ^9.2.0
  go_router: ^17.0.1
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  provider: ^6.1.5+1
  responsive_builder: ^0.7.1
  shared_preferences: ^2.5.4
  universal_web: ^1.1.1+1

dependency_overrides:
  file_selector_linux: 0.9.4
  file_selector_platform_interface: 2.7.0
  file_selector_windows: 0.9.3+5

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

  shaders:
    - shaders/molten_prism.frag
